name: mr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  sensors: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/dice/
    - assets/sounds/
  fonts:
    - family: NotoSansJP-Black
      fonts:
        - asset: fonts/NotoSansJP-Black.ttf
    - family: NotoSansJP-Bold
      fonts:
        - asset: fonts/NotoSansJP-Bold.ttf