name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ----------------------------------------------------------------- #
  # Build for iOS
  # ----------------------------------------------------------------- #

  build_iOS:

    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Flutterのインストール
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      # PATHを通す
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      # パッケージのダウンロード
      - name: Download Flutter packages
        run: flutter pub get

      # 証明書の生成
      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/mr.mobileprovision

      # 署名をする
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      # ipaファイルの出力
      - name: Create ipa file
        run: flutter build ipa --export-options-plist=ExportOptions.plist

      # AppStoreConnectにアップロードする
      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app --type ios -f "./build/ios/ipa/mr.ipa" -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"
